builds:
  - skip: true

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^Merge'
      - '^test'
  groups:
    - title: '🚀 Features'
      regexp: 'feat:'
    - title: '🐛 Bug Fixes'
      regexp: 'fix:'
    - title: '🔨 Others'

release:
  footer: |
    Full Changelog: [{{ .PreviousTag }}...{{ .Tag }}](https://{{ .ModulePath }}/compare/{{ .PreviousTag }}...{{ .Tag }})
