name: "build-image"

on:
  push:
    tags:
      - '*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: service-status
          custom-args: --platform=linux/arm64,linux/amd64
