name: "build-image"

on:
  push:
    tags:
      - '*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tag name
        id: tags
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "输出版本号：$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Build and publish image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: service-status
          additional-image-tags: "${{ steps.tags.outputs.VERSION }}"
          custom-args: --platform=linux/arm64,linux/amd64
